### ISSUE TITLE
是不是哪块写错了？

### ISSUE THREAD

**Issue by jaydiao521** [Rockyzsu/maotai#2]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    product.seckill_by_proc_pool()
  File "/root/jd/maotai/jd_spider_requests.py", line 318, in new_func
    return func(self, *args, **kwargs)
  File "/root/jd/maotai/jd_spider_requests.py", line 343, in seckill_by_proc_pool
    for i in range(self.work_count):
TypeError: 'str' object cannot be interpreted as an integer

**Comment by yf466532479** [comment]
我这也是 报一样的错。。。。。

**Comment by lryyddy** [comment]
登陆完就闪退。。。

**Comment by suluoniu** [comment]
代码部分需要加个 int，但没抢到啊。【抢购失败，返回信息:null】

**Comment by lryyddy** [comment]
> 代码部分需要加个 int，但没抢到啊。【抢购失败，返回信息:null】
哪里加int啊，我没发现

**Comment by jaydiao521** [comment]
> 代码部分需要加个 int，但没抢到啊。【抢购失败，返回信息:null】

求指教需要改哪里
